# Telegram Bot Configuration

# Timeout for task execution in seconds
task_timeout_second: 600

# Length of description text to display in /status
status_desc_length: 30

model_version: auto

# Whitelist for Telegram user unique IDs (integers)
# If empty, all users are allowed to use the bot
whitelist: []
